apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: foo-
nameSuffix: -v1
commonLabels:
  by: kustomization
commonAnnotations:
  note: Hello, I am foo!
images:
  - name: mikehsu0618/api-service
    newName: mikehsu0618/foo
    newTag: v1.0.0
configMapGenerator:
  - name: my-java-server-props
    behavior: create # (create, replace, merge) https://kubectl-book-ja.netlify.app/pages/reference/kustomize.html#configmapgenerator
    literals:
      - ENV_KEY1=ENV_VALUE1
secretGenerator:
  - name: app-tls
    type: Opaque
    literals:
      - key1=base64
resources:
  - deployment.yaml
  - service.yaml
